const InternsData = [
  {
    name: "John Doe",
    age: 40,
    address: "Address45",
    email: "email76@example.com",
    phone: "+1 (555) 134327",
    city: "City50",
    department: "Computer Science",
    occupation: "Occupation33",
    hobbies: "Hobbies62",
    education: "Education79",
  },

  {
    name: "Bob Brown",
    age: 60,
    address: "Address74",
    email: "email39@example.com",
    phone: "+1 (555) 274330",
    city: "City15",
    department: "Computer Science",
    occupation: "Occupation77",
    hobbies: "Hobbies60",
    education: "Education15",
  },
  {
    name: "John Doe",
    age: 50,
    address: "Address20",
    email: "email88@example.com",
    phone: "+1 (555) 753698",
    city: "City7",
    department: "Computer Science",
    occupation: "Occupation69",
    hobbies: "Hobbies66",
    education: "Education21",
  },
  {
    name: "Jane Smith",
    age: 30,
    address: "Address28",
    email: "email53@example.com",
    phone: "+1 (555) 622770",
    city: "City46",
    department: "Computer Science",
    occupation: "Occupation16",
    hobbies: "Hobbies32",
    education: "Education90",
  },
  {
    name: "Jane Smith",
    age: 25,
    address: "Address69",
    email: "email10@example.com",
    phone: "+1 (555) 719934",
    city: "City58",
    department: "Computer Science",
    occupation: "Occupation54",
    hobbies: "Hobbies15",
    education: "Education9",
  },
  {
    name: "John Doe",
    age: 40,
    address: "Address58",
    email: "email78@example.com",
    phone: "+1 (555) 356719",
    city: "City10",
    department: "Computer Science",
    occupation: "Occupation37",
    hobbies: "Hobbies82",
    education: "Education6",
  },
  {
    name: "Michael Lee",
    age: 60,
    address: "Address90",
    email: "email45@example.com",
    phone: "+1 (555) 924285",
    city: "City38",
    department: "Computer Science",
    occupation: "Occupation78",
    hobbies: "Hobbies89",
    education: "Education88",
  },
  {
    name: "Alice Johnson",
    age: 60,
    address: "Address32",
    email: "email28@example.com",
    phone: "+1 (555) 440730",
    city: "City85",
    department: "Arts and Humanities",
    occupation: "Occupation43",
    hobbies: "Hobbies28",
    education: "Education75",
  },
  {
    name: "Alice Johnson",
    age: 25,
    address: "Address89",
    email: "email69@example.com",
    phone: "+1 (555) 372398",
    city: "City52",
    department: "Arts and Humanities",
    occupation: "Occupation13",
    hobbies: "Hobbies58",
    education: "Education98",
  },
  {
    name: "Alice Johnson",
    age: 40,
    address: "Address14",
    email: "email98@example.com",
    phone: "+1 (555) 994138",
    city: "City3",
    department: "Arts and Humanities",
    occupation: "Occupation38",
    hobbies: "Hobbies42",
    education: "Education25",
  },

  {
    name: "Michael Lee",
    age: 40,
    address: "Address91",
    email: "email63@example.com",
    phone: "+1 (555) 175696",
    city: "City72",
    department: "Arts and Humanities",
    occupation: "Occupation5",
    hobbies: "Hobbies40",
    education: "Education38",
  },
  {
    name: "Jane Smith",
    age: 30,
    address: "Address72",
    email: "email63@example.com",
    phone: "+1 (555) 172644",
    city: "City55",
    department: "Environmental Science",
    occupation: "Occupation13",
    hobbies: "Hobbies72",
    education: "Education87",
  },
  {
    name: "John Doe",
    age: 25,
    address: "Address81",
    email: "email59@example.com",
    phone: "+1 (555) 271867",
    city: "City57",
    department: "Environmental Science",
    occupation: "Occupation64",
    hobbies: "Hobbies73",
    education: "Education36",
  },
  {
    name: "Bob Brown",
    age: 25,
    address: "Address47",
    email: "email45@example.com",
    phone: "+1 (555) 339639",
    city: "City42",
    department: "Environmental Science",
    occupation: "Occupation95",
    hobbies: "Hobbies8",
    education: "Education48",
  },
  {
    name: "Bob Brown",
    age: 50,
    address: "Address78",
    email: "email79@example.com",
    phone: "+1 (555) 625535",
    city: "City32",
    department: "Environmental Science",
    occupation: "Occupation42",
    hobbies: "Hobbies7",
    education: "Education0",
  },
  {
    name: "Bob Brown",
    age: 60,
    address: "Address94",
    email: "email21@example.com",
    phone: "+1 (555) 414456",
    city: "City32",
    department: "Environmental Science",
    occupation: "Occupation4",
    hobbies: "Hobbies11",
    education: "Education7",
  },
  {
    name: "Michael Lee",
    age: 60,
    address: "Address46",
    email: "email58@example.com",
    phone: "+1 (555) 851743",
    city: "City38",
    department: "Environmental Science",
    occupation: "Occupation17",
    hobbies: "Hobbies26",
    education: "Education37",
  },
  {
    name: "John Doe",
    age: 50,
    address: "Address61",
    email: "email17@example.com",
    phone: "+1 (555) 747639",
    city: "City92",
    department: "Environmental Science",
    occupation: "Occupation92",
    hobbies: "Hobbies69",
    education: "Education13",
  },

  {
    name: "Alice Johnson",
    age: 60,
    address: "Address94",
    email: "email38@example.com",
    phone: "+1 (555) 871324",
    city: "City90",
    department: "Environmental Science",
    occupation: "Occupation3",
    hobbies: "Hobbies7",
    education: "Education83",
  },
  {
    name: "John Doe",
    age: 50,
    address: "Address44",
    email: "email24@example.com",
    phone: "+1 (555) 560259",
    city: "City58",
    department: "Environmental Science",
    occupation: "Occupation29",
    hobbies: "Hobbies52",
    education: "Education8",
  },
  {
    name: "Michael Lee",
    age: 30,
    address: "Address30",
    email: "email28@example.com",
    phone: "+1 (555) 855617",
    city: "City9",
    department: "Environmental Science",
    occupation: "Occupation19",
    hobbies: "Hobbies56",
    education: "Education82",
  },
  {
    name: "Michael Lee",
    age: 25,
    address: "Address15",
    email: "email64@example.com",
    phone: "+1 (555) 667157",
    city: "City14",
    department: "Health and Medicine",
    occupation: "Occupation93",
    hobbies: "Hobbies15",
    education: "Education4",
  },
  {
    name: "Alice Johnson",
    age: 60,
    address: "Address20",
    email: "email93@example.com",
    phone: "+1 (555) 010204",
    city: "City86",
    department: "Health and Medicine",
    occupation: "Occupation4",
    hobbies: "Hobbies82",
    education: "Education34",
  },
  {
    name: "Alice Johnson",
    age: 30,
    address: "Address38",
    email: "email98@example.com",
    phone: "+1 (555) 283546",
    city: "City85",
    department: "Health and Medicine",
    occupation: "Occupation88",
    hobbies: "Hobbies18",
    education: "Education82",
  },

  {
    name: "Michael Lee",
    age: 25,
    address: "Address67",
    email: "email33@example.com",
    phone: "+1 (555) 980390",
    city: "City22",
    department: "Health and Medicine",
    occupation: "Occupation98",
    hobbies: "Hobbies47",
    education: "Education51",
  },
];

export default InternsData;
