# Generated by Django 5.0.4 on 2024-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('compId', models.AutoField(primary_key=True, serialize=False)),
                ('compName', models.CharField(default='Nash', max_length=250)),
                ('compEmail', models.EmailField(default='example@example.com', max_length=250, unique=True)),
                ('compPassword', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(default='John', max_length=100)),
                ('studentSurname', models.CharField(default='Doe', max_length=100)),
                ('studentEmail', models.EmailField(default='example@example.com', max_length=250, unique=True)),
                ('studentPassword', models.CharField(max_length=250)),
            ],
        ),
    ]
