# Generated by Django 5.0.4 on 2024-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='compPassword',
        ),
        migrations.AddField(
            model_name='company',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='123', max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentPassword',
            field=models.CharField(default='123', max_length=250),
        ),
    ]
