# Generated by Django 5.0.4 on 2024-04-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0008_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcv',
            old_name='cv',
            new_name='cvName',
        ),
    ]
