# Generated by Django 5.0.4 on 2024-04-23 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0009_rename_cv_studentcv_cvname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcv',
            name='studentId',
        ),
        migrations.AddField(
            model_name='studentcv',
            name='student',
            field=models.OneToOneField(default='123', on_delete=django.db.models.deletion.CASCADE, to='interns.student'),
        ),
    ]
