# Generated by Django 5.0.4 on 2024-04-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0011_remove_company_comppassword_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='comp',
        ),
    ]
