# Generated by Django 5.0.4 on 2024-04-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0012_rename_user_company_comp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comp',
            new_name='user',
        ),
    ]
