# Generated by Django 5.0.4 on 2024-04-24 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0013_rename_comp_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('deptId', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirementId', models.AutoField(primary_key=True, serialize=False)),
                ('requirement', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CompDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interns.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interns.departments')),
            ],
        ),
        migrations.CreateModel(
            name='DeptRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interns.departments')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interns.requirement')),
            ],
        ),
    ]
