# Generated by Django 5.0.4 on 2024-04-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0014_departments_requirement_compdepartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptrequirement',
            old_name='departments',
            new_name='department',
        ),
    ]
