# Generated by Django 5.0.4 on 2024-04-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0003_remove_company_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='password',
            new_name='compPassword',
        ),
    ]
