# Generated by Django 5.0.3 on 2024-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0003_remove_user_last_login_alter_intern_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('studentName', models.CharField(default='John', max_length=100)),
                ('studentSurname', models.CharField(default='Doe', max_length=100)),
                ('studentEmail', models.EmailField(default='example@example.com', max_length=100)),
                ('studentPassword', models.CharField(default='123', max_length=100)),
                ('confirmPasswordSt', models.CharField(default='123', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='department',
        ),
        migrations.RemoveField(
            model_name='internskill',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='internskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='portfolioskill',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolioskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='company',
            name='conduct',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='compEmail',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='compName',
            field=models.CharField(default='Nash', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='compPassword',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='confirmPassword',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='company', max_length=10),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Intern',
        ),
        migrations.DeleteModel(
            name='InternSkill',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
