# Generated by Django 5.0.3 on 2024-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0004_student_remove_department_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='compEmail',
            field=models.EmailField(default='example@example.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(default='example@example.com', max_length=100, unique=True),
        ),
    ]
