# Generated by Django 4.2.7 on 2024-04-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0005_alter_company_compemail_alter_student_studentemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='confirmPassword',
        ),
        migrations.RemoveField(
            model_name='student',
            name='confirmPasswordSt',
        ),
    ]
